### ISSUE TITLE
Migrate all statuses to Status types

### ISSUE THREAD

**Issue by beshur** [StoPlay/stoplay-ext#115]
As seen in #111 

Update all places where _status_ is assigned a value in content.js with Status.PLAYING/Status.PAUSED

**Comment by jatin69** [comment]
Can I take this one?

**Comment by beshur** [comment]
@jatin69, yes)

Look for the content.js, the _checkStatus_ method.

Start off _develop_ branch.

**Comment by jatin69** [comment]
Why do you want to update only the places where it is `assigned a value`. 
Why not update all the places? The comparisons and everything else as well?
IMO, that makes the code cleaner. No? Thoughts?

**Comment by endway** [comment]
@jatin69 you can go ahead and update all the places

**Comment by endway** [comment]
Completed in #116
