### ISSUE TITLE
Not working on tunein

### ISSUE THREAD

**Issue by orschiro** [StoPlay/stoplay-ext#120]
Hi all, 

I tested the button with this URL: 

https://tunein.com/radio/Deutschlandfunk-Kultur-896-s6628/

I ensured that the service is enabled but clicking the button doesn't do anything. 

Any ideas?

![image](https://user-images.githubusercontent.com/170947/47343192-d79ae280-d6a5-11e8-9d77-3697e7ab0a57.png)

**Comment by beshur** [comment]
Hi @orschiro.
Looks like the tunein changed their markup and we need to update the script.
We'll get back to it.

**Comment by orschiro** [comment]
Thanks Alex! Can I help somehow? More testing? More feedback?

**Comment by beshur** [comment]
Thank you @orschiro.
I think it's fine for now - just the outdated usecase.
We plan to add tests (#99) at some point.

You can also contribute by fixing this if you want.

**Comment by orschiro** [comment]
Much appreciated, thank you!

**Comment by endway** [comment]
Fixed in #128 
cc @orschiro

**Comment by orschiro** [comment]
Wow, thanks for fixing that. Much appreciated, Oleksandr! :)
