### ISSUE TITLE
Udemy broken

### ISSUE THREAD

**Issue by beshur** [StoPlay/stoplay-ext#163]
**Describe the bug**
Udemy playback is not influencing button.

**To Reproduce**
1. Go to https://www.udemy.com/ (any course)
2. Click Play

**Comment by KeshriAyushi22** [comment]
Hey, I just tried playing the vdo , it started playing.. Is there any specific path which is giving issue?

**Comment by beshur** [comment]
Thank you for asking.

Broken is how our extension works on udemy - it should change its state, be
able to pause playback. See
https://github.com/StoPlay/stoplay-ext/blob/376314be42b1b2c7521de23b7d09eaf486a4fd08/src/content/index.js#L506
