### ISSUE TITLE
Play all on the page - Youtube embedded bug

### ISSUE THREAD

**Issue by beshur** [StoPlay/stoplay-ext#44]
Replication:
1. Get on a page with multiple Youtube embedded clips
2. Play one.
3. Pause it.
4. Press Stoplay from toolbar.
5. All the clips start to play.

**Comment by beshur** [comment]
I don't really have an idea on how to do it. Seems we need half a litre to get hands on this

**Comment by beshur** [comment]
The bug #46 reproduces on this branch on the page with one embed

**Comment by NffS** [comment]
bug #46 is not merged in this brunch

**Comment by beshur** [comment]
I will continue testing on an integrated branch
