### ISSUE TITLE
Add optional notifications with track name

### ISSUE THREAD

**Issue by beshur** [StoPlay/stoplay-ext#54]
Use browser Notifications for displaying arist/track name

**Comment by endway** [comment]
![screen shot 2016-05-16 at 16 49 09](https://cloud.githubusercontent.com/assets/1341174/15291371/2d65e65c-1b86-11e6-91b9-ab4fe9bd961d.png)
Prepaid edition 😆

**Comment by endway** [comment]
Done in d0ecb7fbc0c4727596ef96b2cee65275235ad7bd
